version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: steeve05/car-page:latest
    ports: 
       - "8080:8080"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Підключаємо кастомний конфіг
      - ./app:/usr/share/nginx/html/  # Статичні файли з папки app
    ports:
      - "80:80"
    depends_on:
      - backend


  # node-exporter:
  #   image: prom/node-exporter:latest
  #   ports:
  #     - "9100:9100"

  # prometheus:
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin # замініть на свій пароль

