name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: 
      - completed

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image DockerHub
      run:  docker pull steeve05/car-page:latest
   
    - name: Delete old docker container
      run:  docker rm -f car-page-container || true

    - name: Run Latest Docker Container
      run:  docker run -d -p 8080:80 --name car-page-container steeve05/car-page
   




