name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: 
      - completed

jobs:
  build:

    runs-on: self-hosted

    steps:

    - name: Log in to Docker Hub
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    
    - name: Pull Docker image DockerHub
      run:  sudo docker pull steeve05/car-page:latest
   
    - name: Delete old docker container
      run:  sudo docker rm -f car-page-container || true


    - name: Run Latest Docker Container
      run:  sudo docker run -d -p 8080:80 --name car-page-container steeve05/car-page:latest
   




