name: CI Pipeline

on:
    
    push:
      branches: [ "master" ] 
  
jobs:
    build:
  
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
      
        - name: Log in to Docker Hub
          env: 
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        
        - name: Install Docker Compose
          run: sudo apt-get update && sudo apt-get install -y docker-compose
        
        - name: Build and push Docker image to Docker Hub
          run: |
            sudo docker-compose build
            sudo docker-compose push 
      


